language: php
php:
  - 7.1

os:
  - linux
sudo: required
dist: trusty

before_script:
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - sudo mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin
  - composer self-update
  - composer install --prefer-source --no-interaction

install:
  - composer require php-coveralls/php-coveralls
  - composer require jakub-onderka/php-parallel-lint

script:
  - mkdir -p build/logs
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v


